# Generated by Django 2.0.7 on 2018-09-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inserzione',
            fields=[
                ('titolo', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=500)),
                ('pagina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='utente',
            unique_together={('username', 'email')},
        ),
        migrations.AddField(
            model_name='inserzione',
            name='utente',
            field=models.ManyToManyField(related_name='utente', to='feed.Utente'),
        ),
        migrations.AddField(
            model_name='inserzione',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to='feed.Utente'),
        ),
        migrations.AlterUniqueTogether(
            name='inserzione',
            unique_together={('titolo', 'id')},
        ),
    ]
