# Generated by Django 2.0.7 on 2018-10-09 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inserzione',
            fields=[
                ('titolo', models.CharField(max_length=50)),
                ('id', models.CharField(default='zDwUyPfDVACVL7knsnHi5a', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('descrizione', models.CharField(default='', max_length=500)),
                ('indirizzo', models.CharField(max_length=50)),
                ('max_prezzo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partita_iva', models.CharField(max_length=50, unique=True)),
                ('luogo', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AddField(
            model_name='inserzione',
            name='interessati',
            field=models.ManyToManyField(default=[], related_name='interessati', to='feed.Profile'),
        ),
        migrations.AddField(
            model_name='inserzione',
            name='offerenti',
            field=models.ManyToManyField(default=[], related_name='offerenti', to='feed.Profile'),
        ),
        migrations.AddField(
            model_name='inserzione',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to='feed.Profile'),
        ),
    ]
