# Generated by Django 2.0.7 on 2018-09-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserzione',
            name='indirizzo',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inserzione',
            name='prezzo',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inserzione',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feed.Pagina'),
        ),
    ]
