# Generated by Django 2.0.7 on 2018-09-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_inserzione_prezzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inserzione',
            name='indirizzo',
        ),
    ]
