# Generated by Django 2.0.7 on 2018-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20181101_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserzione',
            name='prezzo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inserzione',
            name='id',
            field=models.CharField(default='tPhpgffZAHbBTwzrctN8fc', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
