# Generated by Django 2.0.7 on 2018-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_inserzione_indirizzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserzione',
            name='indirizzo',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inserzione',
            name='prezzo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
