# Generated by Django 2.1.3 on 2018-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20181121_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserzione',
            name='id',
            field=models.CharField(default='KZCa7mxMTdX7p87kZwdHtY', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
