# Generated by Django 2.0.7 on 2018-10-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20180925_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inserzione',
            name='pagina',
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
