# Generated by Django 2.0.7 on 2018-10-02 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20181002_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserzione',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=15, primary_key=True, serialize=False),
        ),
    ]
