# Generated by Django 2.0.7 on 2018-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20181002_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserzione',
            name='id',
            field=models.CharField(default='apqchWfdxftEAXjN76FAuC', max_length=30, primary_key=True, serialize=False),
        ),
    ]
